# Generated by Django 3.1 on 2021-03-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='id_number',
            new_name='code',
        ),
    ]
