# Generated by Django 3.1 on 2021-04-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0003_setup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(blank=True),
        ),
    ]
